### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by htdat** [htdat/TeachYourselfCS-vi#2]
- [ ] Thêm một phần đầu để giới thiệu và link tới các mục khác. 
- [ ] Viết phần note của cá nhân mình.
- [ ] Kêu gọi tạo issues nếu có lỗi chính tả hay lỗi dịch
